name: Build sing-box package for Entware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]
        target-arch: [mipsel]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-mipsel-linux-gnu python2.7

    - name: Prepare Entware environment
      run: |
        git clone https://github.com/Entware/Entware.git
        cd Entware
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Copy sing-box package 
      run: | 
        cd Entware
        mkdir -p package/sing-box-go
        cp -r $GITHUB_WORKSPACE/sing-box-go package/sing-box-go/
    - name: Create .config 
      run: | 
        echo "CONFIG_TARGET_mipsel=y" > Entware/.config
        echo "CONFIG_TARGET_mipsel_24kc=y" >> Entware/.config
        echo "CONFIG_PACKAGE_sing-box-go=y" >> Entware/.config
    - name: Build sing-box package
      run: |
        cd Entware
        make defconfig 
        make package/sing-box-go/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sing-box-package
        path: bin/packages/mipsel_24kc/sing-box-go*.ipk
