name: Build sing-box package for Entware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]
        target-arch: [mipsel]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential mipsel-linux-gnu-gcc

    - name: Prepare Entware environment
      run: |
        git clone https://github.com/Entware/Entware.git
        cd Entware
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build sing-box package
      run: |
        cd sing-box-keenetic
        cp -r sing-box-go/ ../Entware/package/
        cd ../Entware
        make menuconfig # Тут потребуется выбрать sing-box-go из меню
        make package/sing-box-go/compile V=s

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sing-box-package
        path: bin/packages/mipsel_24kc/sing-box-go*.ipk
