name: Build Sing-Box for Entware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for MIPSEL Architecture
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - mipsel
        go_version:
          - '1.19'
    
    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Go
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      
      # Шаг 3: Установка кросс-компилятора
      - name: Install mipsel compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mipsel-linux-gnu

      # Шаг 4: Установка зависимостей для сборки Entware
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential unzip git cmake pkg-config

      # Шаг 5: Настройка среды для сборки Entware
      - name: Prepare Entware build environment
        run: |
          git clone https://github.com/Entware/Entware.git entware
          cd entware
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Шаг 6: Клонирование исходников Sing-Box
      - name: Download Sing-Box source code
        run: |
          cd entware
          mkdir -p package/sing-box-go
          cp -r $GITHUB_WORKSPACE/* package/sing-box-go/
          ./scripts/feeds install -a

      # Шаг 7: Настройка конфигурации для сборки
      - name: Configure build for MIPSEL
        run: |
          cd entware
          make menuconfig
        env:
          TARGET_ARCH: ${{ matrix.target_arch }}
          PATH: "/opt/mipsel-linux-uclibc/bin:$PATH"

      # Шаг 8: Сборка пакета
      - name: Build package
        run: |
          cd entware
          make package/sing-box-go/compile V=s

      # Шаг 9: Сохранение собранного пакета
      - name: Upload compiled package
        uses: actions/upload-artifact@v3
        with:
          name: sing-box-${{ matrix.target_arch }}-${{ matrix.go_version }}
          path: entware/bin/packages/mipsel/*/*.ipk
